version: '3'

services:
  orchestrator:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app/
    command: python3.10 multi.py --as orchestrator --jlog -c topology/docker.yaml --novenv
    volumes: 
      - ./topology:/app/topology
      - ./data:/data
    labels:
      exorde: monitor

  spotting:
    build:
      context: .
      dockerfile: Dockerfile.spot
    restart: always
    working_dir: /app/
    command: python3.10 multi.py --as spotting --jlog -c topology/docker.yaml --novenv
    volumes:
      - ./topology:/app/topology
    labels:
      exorde: monitor

  scraper_one:
    build:
      context: .
      dockerfile: Dockerfile.scrap
    restart: always
    working_dir: /app/
    command: python3.10 multi.py --as scraper_one --jlog -c topology/docker.yaml --novenv
    volumes:
      - ./topology:/app/topology
    labels:
      exorde: monitor

  scraper_two:
    build:
      context: .
      dockerfile: ./Dockerfile.spot
    restart: always
    working_dir: /app/
    command: python3.10 multi.py --as scraper_two --jlog -c topology/docker.yaml --novenv
    volumes:
      - ./topology:/app/topology
    labels:
      exorde: monitor

  monitor:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app/
    command: python3.10 multi.py --as monitor -c topology/docker.yaml --novenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./topology:/app/topology
    ports:
      - "8004:8004"
